Repository census-instrumentation/opencensus-go, pull requests merged in 2018-03, with the labels that each got.

#591 Remove unnecessary defer in Span.End, shaving significant time
  trace/trace.go
Labels: performance

#601 Split default client and server views for the HTTP plugin
  plugin/ocgrpc/client_metrics.go
  plugin/ocgrpc/server_metrics.go
  plugin/ochttp/client_test.go
  plugin/ochttp/server_test.go
  plugin/ochttp/stats.go
Labels: api-breaking

#603 Remove NoStats
  plugin/ocgrpc/client.go
  plugin/ocgrpc/server.go
  plugin/ocgrpc/trace_common_test.go
  plugin/ochttp/client.go
  plugin/ochttp/client_test.go
  plugin/ochttp/server.go
  plugin/ochttp/trace_test.go
Labels: api-breaking

#641 Remove error from stats.{Float,Int}64Measure signatures
  README.md
  examples/helloworld/main.go
  exporter/prometheus/example/main.go
  exporter/prometheus/prometheus_test.go
  exporter/stackdriver/examples/stats/main.go
  exporter/stackdriver/stats_test.go
  internal/readme/stats.go
  plugin/ocgrpc/client_metrics.go
  plugin/ocgrpc/server_metrics.go
  plugin/ochttp/stats.go
  stats/benchmark_test.go
  stats/example_test.go
  stats/measure_float64.go
  stats/measure_int64.go
  stats/view/benchmark_test.go
  stats/view/example_test.go
  stats/view/view_measure_test.go
  stats/view/view_test.go
  stats/view/worker_test.go
Labels: api-breaking, do not merge
